# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

variables:
  MPLBACKEND: Agg
  RSMVERSION: 7.1.0
  TESTDIR: $(Build.SourcesDirectory)\rsmcode\tests

trigger: none
pr:
- master

jobs:

- job: 'RSMToolTests'
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    parallel: 5

  steps:
  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH

  - script: |
      git clone https://github.com/EducationalTestingService/rsmtool.git rsmcode
    displayName: "Clone RSMTool repository"

  - script: |
      conda update --quiet --yes conda
      conda info -a
    displayName: "Update conda"

  - script: |
      conda create --name rsmdev --yes --quiet -c conda-forge -c ets python=%PYTHON_VERSION%
      conda init cmd.exe
      CALL activate rsmdev
      pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple rsmtool==%RSMVERSION%
    displayName: 'Install TestPyPI package for RSMTool'

  - powershell: ./DistributeTests.ps1 
    displayName: 'PowerShell Script to distribute tests'

  - script: |
      CALL activate rsmdev
      echo $(pytestfiles)
      nosetests --with-xunit $(pytestfiles)
    displayName: 'Run tests'

  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    inputs:
      testResultsFiles: 'nosetests.xml'
      testRunTitle: 'RSMTool tests'
    condition: succeededOrFailed()
